repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.3
    hooks:
      - id: ruff-check
      - id: ruff-format
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv run mypy
        language: system
        pass_filenames: false
        types: [python]
      - id: pytest
        name: pytest
        entry: uv run pytest -x
        language: system
        pass_filenames: false
        types: [python]
